### ISSUE TITLE
Support for long read data

### ISSUE THREAD

**Issue by hexylena** [fastqe/fastqe#10]
It looks like it is [currently limited to 500 bases](https://github.com/lonsbio/fastqe/blob/master/fastqe/fastqe.py#L197), and I "need" this in my Nanopore visualisation workflow, now that I've got fastqe in Galaxy.

**Comment by lonsbio** [comment]
Thanks @hexylena for the the Galaxy recipe! Your timing is impeccable, as long read support is ready to go and I plan to release in time for BCC2020 next week. 

Currently, it is implemented as an option to allow for reads up to MAX_LENGTH, and asks the user to provide that length. 

Would that suit your purposes?

![long_read_demo](https://user-images.githubusercontent.com/2631592/87361566-e038f800-c5af-11ea-8f3b-3f137e4148cf.png)

**Comment by hexylena** [comment]
Sure, no dramas. I saw the abstract and couldn't resist throwing it in Galaxy, it's going to be great as an illustrative and teaching tool in the training materials.

Yeah, a --long flag'll be perfect, easy enough.

**Comment by lonsbio** [comment]
Added long read support in v0.2.x release
