### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by ewels** [fastqe/fastqe#15]
It was mentioned on the BOSC Discord chat that the project needs a code of conduct. A relatively hidden feature in GitHub is a tool to add a Code of Conduct for you - see https://github.com/fastqe/fastqe/community/code-of-conduct/new?template=contributor-covenant (or click through from _Insights_ > _Community_ > _Code of Conduct_).

This is probably a task for @lonsbio as owner of the project. Once added it's just a regular file so anyone can go to down on the customisation 😉 💥

**Comment by lonsbio** [comment]
Thanks for the tip @ewels  👏  - done!

https://github.com/fastqe/fastqe/blob/master/CODE_OF_CONDUCT.md
